version: '3.5'

services:

  etcd0:
    image: quay.io/coreos/etcd
    network_mode: host
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:12379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${HOST_IP}:12379

  mon1:
    image: flaviostutz/ceph-monitor
    network_mode: host
    environment:
      - CREATE_CLUSTER=true
      - ETCD_URL=http://${HOST_IP}:12379
      - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:16789
      - MONITOR_BIND_PORT=16789

  # mon2:
  #   image: flaviostutz/ceph-monitor
  #   ports:
  #     - 26789:6789
  #   environment:
  #     - ETCD_URL=http://${HOST_IP}:12379
  #     - PEER_MONITOR_HOSTS=${HOST_IP}:16789
  #     - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:26789

  # mon3:
  #   image: flaviostutz/ceph-monitor
  #   ports:
  #     - 36789:6789
  #   environment:
  #     - ETCD_URL=http://${HOST_IP}:12379
  #     - PEER_MONITOR_HOSTS=${HOST_IP}:16789
  #     - MONITOR_ADVERTISE_ADDRESS=${HOST_IP}:36789

  osd1:
    build: .
    network_mode: host
    pid: host
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://${HOST_IP}:12379
      - OSD_CRUSH_HOST=osd1
      - OSD_CRUSH_RACK=rack1
      # - OSD_PUBLIC_IP=${HOST_IP}
      # - OSD_CLUSTER_IP=${HOST_IP}

  osd2:
    build: .
    network_mode: host
    pid: host
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://${HOST_IP}:12379
      - OSD_CRUSH_HOST=osd2
      - OSD_CRUSH_RACK=rack2

  osd3:
    build: .
    network_mode: host
    pid: host
    environment:
      - MONITOR_HOSTS=${HOST_IP}:16789
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
      - ETCD_URL=http://${HOST_IP}:12379
      - OSD_CRUSH_HOST=osd3
      - OSD_CRUSH_RACK=rack3
