version: '3.5'

services:

  mon1:
    image: flaviostutz/ceph-monitor
    environment:
      - LOG_LEVEL=1

  osd1:
    build: .
    environment:
      - LOG_LEVEL=10
      - PEER_MONITOR_HOST=mon1
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
    volumes:
      - /mnt/sdb-osd1:/var/lib/ceph/osd

  osd2:
    build: .
    environment:
      - LOG_LEVEL=10
      - PEER_MONITOR_HOST=mon1
      - OSD_EXT4_SUPPORT=true
      - OSD_JOURNAL_SIZE=512
    volumes:
      - osd2:/var/lib/ceph/osd

volumes:
  osd2:

